# #123
GET http://localhost:12451/file/test
Content-Type: application/x-www-form-urlencoded

dir=upload


# # 1
# GET http://localhost:12450/dir/1623256741260
# Content-Type: application/x-www-form-urlencoded

# id=1623256741260

# 23
DELETE http://localhost:12450/file/upload_d6a14eec1c98718906c689f8f75e865c.jpg
Content-Type: application/x-www-form-urlencoded
